sudo: false
cache: bundler

language: ruby

matrix:
  allow_failures:
    - rvm: jruby
    - rvm: rbx-2

rvm:
  - 2.1
  - 2.2
  - 2.3.1
  - jruby
  - rbx-2

script:
  - bundle exec rubocop
  - bundle exec rspec spec
  - bundle exec rake test
  - bundle exec rake test:integration

services:
  - redis
  - rabbitmq

addons:
  postgresql: "9.4"
