sudo: false
cache: bundler

language: ruby

matrix:
  exclude:
    # Rails 5.0 dropped support for Ruby <2.2
    - rvm: 2.1
      gemfile: Gemfile.activejob50

rvm:
  - 2.1
  - 2.2.2
  - 2.3.3

gemfile:
  - Gemfile.activejob42
  - Gemfile.activejob50

before_install:
  - gem update --system
  - gem install bundler

script:
  - bundle exec rubocop
  - bundle exec rspec spec
  - bundle exec rake test

services:
  - redis
  - rabbitmq

addons:
  postgresql: "9.6"
