sudo: false
cache: bundler

language: ruby

matrix:
  allow_failures:
    - rvm: jruby
    - rvm: rbx-2
  exclude:
    # Rails 5.0 dropped support for Ruby <2.2
    - rvm: 2.0
      gemfile: Gemfile.activejob50
    - rvm: 2.1
      gemfile: Gemfile.activejob50

rvm:
  - 2.0
  - 2.1
  - 2.2.2
  - 2.3.1
  - jruby
  - rbx-2

gemfile:
  - Gemfile.activejob42
  - Gemfile.activejob50

script:
  - bundle exec rubocop
  - bundle exec rspec spec
  - bundle exec rake test

services:
  - redis
  - rabbitmq

addons:
  postgresql: "9.4"
